2018-01-24 18:25:08,454 -0800 INFO pid=2376 7780:MainThread      logging_config.py:295 OS: Windows/6.1-SP1
2019-01-24 18:25:08,454 -0800 INFO pid=2376 7780:MainThread      logging_config.py:298 Backup and Sync (build 3.38.7642.3857)
2018-01-24 18:25:08,456 -0800 INFO pid=2376 7780:MainThread      logging_config.py:299 SSL: OpenSSL 1.0.2m  2 Nov 2017
2018-01-24 18:25:18,563 -0800 INFO pid=2376 5712:ExternalBrowserFlow proxy_manager.py:141 Exception while auto resolving proxy.
Traceback (most recent call last):
  File "common\proxy_manager.py", line 135, in _GetProxyInfoForUrl
  File "windows\system_proxy_resolver.py", line 96, in GetProxyForUrlViaWPAD
  File "windows\system_proxy_resolver.py", line 155, in _GetProxy
ProxyInfoResolutionError: ProxyInfoResolutionError: inner_error=(12180, 'WinHttpGetProxyForUrl', 'The Proxy Auto-configuration URL was not found.')
2018-01-24 18:25:18,565 -0800 INFO pid=2376 5712:ExternalBrowserFlow service.py:132 Creating singleton service instance of '<class 'common.net.dapper.DapperService'>'
